import { redirect } from 'next/navigation';
import { ReadError, ForbiddenRead } from '../../../../../components/read-models';
import type { AdminRefund } from '../../../../../lib/admin-api';
import { adminGet, queryString } from '../../../../../lib/admin-api';
import { isLocale } from '../../../../../lib/i18n';
import { messagesFor } from '../../../../../messages';
import { mayRenderAdminPage } from '../../../../../lib/session';
type SearchParams = Record<string, string | string[] | undefined>;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function date(value: string, locale: string) { return new Intl.DateTimeFormat(locale === 'ar' ? 'ar-JO' : 'en-JO', { timeZone: 'Asia/Amman', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
export default async function Page({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<SearchParams> }) { const { locale } = await params; if (!isLocale(locale)) redirect('/en'); if (!await mayRenderAdminPage()) return <ForbiddenRead locale={locale} />; const t = messagesFor(locale); const raw = await searchParams; const query = Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, one(value)]).filter((entry): entry is [string, string] => typeof entry[1] === 'string' && entry[1].length > 0)); try { const rows = await adminGet<AdminRefund[]>(`/admin/refunds${queryString({ status: query.status, paymentId: query.paymentId, bookingId: query.bookingId, customerId: query.customerId, companyId: query.companyId, createdFrom: query.createdFrom, createdTo: query.createdTo })}`); return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">{t.phase14f}</div><h1>{t.refundsTitle}</h1><p>{t.paymentsDescription}</p></div></div><section className="panel"><div className="section-heading"><h2>{t.refundResults}</h2><span>{rows.length} {t.results}</span></div>{!rows.length ? <p className="empty-state">{t.noRefunds}</p> : <div className="table-wrap"><table><thead><tr><th>{t.booking}</th><th>{t.customer}</th><th>{t.status}</th><th>{t.amount}</th><th>{t.reason}</th><th>{t.created}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><a href={`/${locale}/finance/payments/${row.paymentId}`}>{row.booking.bookingNumber}</a></td><td>{row.customer.name ?? row.customer.phone}</td><td>{row.status}</td><td>{row.amount} JOD</td><td>{row.reason}</td><td>{date(row.createdAt, locale)}</td></tr>)}</tbody></table></div>}</section></div>; } catch (error) { return <ReadError locale={locale} error={error} />; } }
