import Link from 'next/link';
import type { Locale } from '../lib/i18n';
import type { AdminLocations, AdminNotificationDelivery, AdminNotificationDeliveryDetail } from '../lib/admin-api';
import { messagesFor } from '../messages';

function date(value: string | null, locale: Locale) {
  if (!value) return '—';
  return new Intl.DateTimeFormat(locale === 'ar' ? 'ar-JO' : 'en-JO', { timeZone: 'Asia/Amman', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
}
function status(value: string) { return value.replaceAll('_', ' '); }

export function NotificationsView({ locale, rows, query }: { locale: Locale; rows: AdminNotificationDelivery[]; query: Record<string, string | string[] | undefined> }) {
  const t = messagesFor(locale);
  const value = (key: string) => typeof query[key] === 'string' ? query[key] as string : '';
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14G</div><h1>{t.notificationsTitle}</h1><p>{t.notificationsDescription}</p></div></div>
    <section className="panel"><form className="filter-bar" method="get"><label>{t.status}<select name="status" defaultValue={value('status')}><option value="">{t.allStatuses}</option>{['PENDING', 'SENDING', 'SENT', 'FAILED'].map(item => <option key={item}>{item}</option>)}</select></label><label>{t.notificationType}<input name="type" defaultValue={value('type')} /></label><label>{t.notificationCategory}<input name="category" defaultValue={value('category')} /></label><label>{t.recipientId}<input name="userId" defaultValue={value('userId')} /></label><label>{t.referenceType}<input name="referenceType" defaultValue={value('referenceType')} /></label><label>{t.referenceId}<input name="referenceId" defaultValue={value('referenceId')} /></label><label>{t.createdFrom}<input type="datetime-local" name="createdFrom" defaultValue={value('createdFrom')} /></label><label>{t.createdTo}<input type="datetime-local" name="createdTo" defaultValue={value('createdTo')} /></label><button type="submit">{t.applyFilters}</button><Link className="button-link" href={`/${locale}/communications/notifications`}>{t.clearFilters}</Link></form></section>
    <section className="panel"><div className="section-heading"><h2>{t.notificationResults}</h2><span>{rows.length} {t.results}</span></div>{!rows.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.created}</th><th>{t.notificationType}</th><th>{t.recipient}</th><th>{t.reference}</th><th>{t.notificationState}</th><th>{t.deliveryState}</th><th>{t.attempts}</th><th>{t.deliveryError}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Link href={`/${locale}/communications/notifications/${row.id}`}>{date(row.createdAt, locale)}</Link><br /><small>{row.channel}</small></td><td>{status(row.notification.type)}<br /><small>{row.notification.category}</small></td><td><code>{row.notification.userId}</code></td><td>{row.notification.booking ? <Link href={`/${locale}/operations/bookings/${row.notification.booking.id}`}>{row.notification.booking.bookingNumber}</Link> : <><span>{row.notification.referenceType ?? '—'}</span><br /><small>{row.notification.referenceId ?? '—'}</small></>}</td><td>{row.notification.readAt ? t.read : row.notification.deliveredAt ? t.delivered : t.notDelivered}</td><td>{status(row.status)}<br /><small>{row.sentAt ? `${t.sent}: ${date(row.sentAt, locale)}` : row.nextAttemptAt ? `${t.nextAttempt}: ${date(row.nextAttemptAt, locale)}` : t.notDelivered}</small></td><td>{row.attempts}</td><td>{row.lastError ?? '—'}</td></tr>)}</tbody></table></div>}</section>
    <p className="read-only-note">{t.notificationPrivacy}</p>
  </div>;
}

export function NotificationDetailView({ locale, row }: { locale: Locale; row: AdminNotificationDeliveryDetail }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14G</div><h1>{t.notificationDetailTitle}</h1><p>{status(row.notification.type)} · {row.notification.userId}</p></div><Link className="button-link" href={`/${locale}/communications/notifications`}>{t.backToList}</Link></div>
    <section className="detail-grid"><article className="panel"><h2>{t.summary}</h2><dl className="detail-list"><dt>{t.notificationState}</dt><dd>{row.notification.readAt ? t.read : row.notification.deliveredAt ? t.delivered : t.notDelivered}</dd><dt>{t.deliveryState}</dt><dd>{status(row.status)}</dd><dt>{t.channel}</dt><dd>{row.channel}</dd><dt>{t.notificationCategory}</dt><dd>{row.notification.category}</dd><dt>{t.recipientId}</dt><dd><code>{row.notification.userId}</code></dd><dt>{t.reference}</dt><dd>{row.notification.referenceType ?? '—'} / {row.notification.referenceId ?? '—'}</dd><dt>{t.eventReference}</dt><dd><code>{row.notification.eventKey ?? '—'}</code></dd><dt>{t.created}</dt><dd>{date(row.createdAt, locale)}</dd><dt>{t.sent}</dt><dd>{date(row.sentAt, locale)}</dd><dt>{t.delivered}</dt><dd>{date(row.notification.deliveredAt, locale)}</dd><dt>{t.providerReference}</dt><dd><code>{row.providerReference ?? '—'}</code></dd><dt>{t.deliveryError}</dt><dd>{row.lastError ?? '—'}</dd></dl></article><article className="panel"><h2>{t.safePayload}</h2><pre className="json-view">{JSON.stringify(row.safePayload, null, 2)}</pre><p className="read-only-note">{t.notificationPrivacy}</p></article></section>
    <section className="panel"><h2>{t.deliveryHistory}</h2>{!row.attemptsHistory.length ? <p className="empty-state">{t.noDeliveryAttempts}</p> : <ol className="timeline">{row.attemptsHistory.map(attempt => <li key={attempt.id}><strong>#{attempt.attemptNumber} · {status(attempt.status)}</strong><span>{date(attempt.createdAt, locale)}</span><small>{attempt.providerReference ? `${t.providerReference}: ${attempt.providerReference}` : ''}{attempt.error ? ` · ${attempt.error}` : ''}</small></li>)}</ol>}</section>
  </div>;
}

export function LocationsView({ locale, data, query }: { locale: Locale; data: AdminLocations; query: Record<string, string | string[] | undefined> }) {
  const t = messagesFor(locale);
  const value = (key: string) => typeof query[key] === 'string' ? query[key] as string : '';
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14G</div><h1>{t.locationsTitle}</h1><p>{t.locationsDescription}</p></div><small>{t.asOf}: {date(data.generatedAt, locale)}<br />{t.locationFreshnessWindow}: {data.locationMaxAgeMinutes} {t.minutes}</small></div>
    <section className="panel"><form className="filter-bar" method="get"><label>{t.companyId}<input name="companyId" defaultValue={value('companyId')} /></label><label>{t.teamId}<input name="teamId" defaultValue={value('teamId')} /></label><label>{t.teamStatus}<select name="teamStatus" defaultValue={value('teamStatus')}><option value="">{t.allStatuses}</option>{['AVAILABLE', 'BUSY', 'OFFLINE', 'PAUSED'].map(item => <option key={item}>{item}</option>)}</select></label><label>{t.freshness}<select name="freshness" defaultValue={value('freshness')}><option value="">{t.allFreshness}</option><option value="FRESH">{t.fresh}</option><option value="STALE">{t.stale}</option><option value="NEVER_REPORTED">{t.neverReported}</option></select></label><label>{t.locationAvailability}<select name="locationAvailability" defaultValue={value('locationAvailability')}><option value="">{t.allAvailability}</option><option value="AVAILABLE">{t.locationAvailable}</option><option value="MISSING">{t.locationMissing}</option></select></label><button type="submit">{t.applyFilters}</button><Link className="button-link" href={`/${locale}/operations/locations`}>{t.clearFilters}</Link></form></section>
    <section className="panel"><div className="section-heading"><h2>{t.teamLocations}</h2><span>{data.teams.length} {t.results}</span></div>{!data.teams.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.team}</th><th>{t.company}</th><th>{t.teamStatus}</th><th>{t.location}</th><th>{t.locationReported}</th><th>{t.freshness}</th></tr></thead><tbody>{data.teams.map(team => <tr key={team.id}><td>{team.name}<br /><small>{team.internalCode}</small></td><td>{team.company.name}<br /><small>{team.company.status}</small></td><td>{status(team.status)}{!team.active && ` · ${t.inactive}`}</td><td>{team.latitude !== null && team.longitude !== null ? <code>{team.latitude}, {team.longitude}</code> : t.locationMissing}</td><td>{date(team.locationAt, locale)}</td><td>{status(team.freshness)}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel"><h2>{t.serviceAreas}</h2>{!data.serviceAreas.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.company}</th><th>{t.serviceArea}</th><th>{t.coordinates}</th><th>{t.radius}</th><th>{t.status}</th></tr></thead><tbody>{data.serviceAreas.map(area => <tr key={area.id}><td>{area.company.name}</td><td>{area.name}</td><td><code>{area.latitude}, {area.longitude}</code></td><td>{area.radiusKm} km</td><td>{area.active ? t.active : t.inactive}</td></tr>)}</tbody></table></div>}</section>
    <p className="read-only-note">{t.locationPrivacy}</p>
  </div>;
}
