import Link from 'next/link';
import type { Locale } from '../lib/i18n';
import type { AdminBookingDetail, AdminBookingSummary, AdminCustomerDetail, AdminCustomerSummary, AdminDashboard, AdminUserSummary, AuditDetail, AuditSummary, DispatchMonitoring, RoleGrant } from '../lib/admin-api';
import { ApiError } from '../lib/api';
import { ProvisionUserForm, RevokeGrantButton, StatusControl } from './identity-actions';
import { messagesFor } from '../messages';
import { BookingActions } from './booking-actions';

function date(value: string, locale: Locale) {
  return new Intl.DateTimeFormat(locale === 'ar' ? 'ar-JO' : 'en-JO', { timeZone: 'Asia/Amman', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
}

function status(value: string) { return value.replaceAll('_', ' '); }

function ErrorState({ locale, error, notFound = false }: { locale: Locale; error: unknown; notFound?: boolean }) {
  const t = messagesFor(locale);
  const apiError = error instanceof ApiError ? error : undefined;
  return <section className="panel" role="alert"><div className="phase-tag">14B</div><h1>{notFound ? t.notFoundTitle : apiError?.status === 403 ? t.forbiddenTitle : t.readErrorTitle}</h1>
    <p>{notFound ? t.notFoundDescription : apiError?.status === 403 ? t.forbiddenDescription : t.readErrorDescription}</p>
    {apiError?.requestId && <small>{t.requestId}: {apiError.requestId}</small>}</section>;
}

export function ReadError({ locale, error, notFound }: { locale: Locale; error: unknown; notFound?: boolean }) { return <ErrorState locale={locale} error={error} notFound={notFound} />; }

export function ForbiddenRead({ locale }: { locale: Locale }) { return <ErrorState locale={locale} error={new ApiError(403, 'FORBIDDEN_RESOURCE', 'Admin access required.')} />; }

function CountList({ values, locale }: { values: { status: string; count: number }[]; locale: Locale }) {
  const t = messagesFor(locale);
  if (!values.length) return <p className="empty-state">{t.emptyState}</p>;
  return <ul className="metric-list">{values.map(row => <li key={row.status}><span>{status(row.status)}</span><strong>{row.count}</strong></li>)}</ul>;
}

export function DashboardView({ locale, data }: { locale: Locale; data: AdminDashboard }) {
  const t = messagesFor(locale);
  const cards = [
    [t.noTeamAvailable, data.attention.noTeamAvailable], [t.rejected, data.attention.rejected], [t.teamNoShow, data.attention.teamNoShow],
    [t.paymentReconciliation, data.attention.paymentReconciliation], [t.refundPending, data.attention.refundPending], [t.staleTeamLocations, data.providers.staleTeamLocations],
    [t.paymentPending, data.finance.paymentPending], [t.paymentFailed, data.finance.paymentFailed], [t.cashCollectedUnreconciled, data.finance.cashCollectedUnreconciled],
    [t.settlementsReadyForReview, data.finance.settlementsReadyForReview], [t.settlementDiscrepancies, data.finance.settlementDiscrepancies], [t.notificationFailures, data.notifications.failed],
  ];
  return <div className="dashboard-stack">
    <div className="page-heading"><div><div className="phase-tag">14B</div><h1>{t.dashboardTitle}</h1><p>{t.dashboardDescription}</p></div><small>{t.asOf}: {date(data.generatedAt, locale)} ({t.ammanTime})</small></div>
    <section className="metric-grid" aria-label={t.attentionTitle}>{cards.map(([label, value]) => <article className="metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <div className="dashboard-grid">
      <section className="panel"><h2>{t.bookingStatus}</h2><CountList values={data.bookingsByStatus} locale={locale} /></section>
      <section className="panel"><h2>{t.assignmentStatus}</h2><CountList values={data.assignmentsByStatus} locale={locale} /></section>
      <section className="panel"><h2>{t.companyStatus}</h2><CountList values={data.providers.companiesByStatus} locale={locale} /></section>
      <section className="panel"><h2>{t.teamStatus}</h2><CountList values={data.providers.teamsByStatus} locale={locale} /></section>
    </div>
    <section className="panel"><div className="section-heading"><h2>{t.recentDispatchAttempts}</h2><Link href={`/${locale}/operations/bookings`}>{t.viewBookings}</Link></div>
      {!data.recentDispatchAttempts.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.booking}</th><th>{t.outcome}</th><th>{t.reason}</th><th>{t.created}</th></tr></thead><tbody>{data.recentDispatchAttempts.map(row => <tr key={row.id}><td><Link href={`/${locale}/operations/bookings/${row.bookingId}`}>{row.bookingNumber}</Link></td><td>{status(row.outcome)}</td><td>{row.reason ?? '—'}</td><td>{date(row.createdAt, locale)}</td></tr>)}</tbody></table></div>}
    </section>
  </div>;
}

export function BookingsView({ locale, rows, query }: { locale: Locale; rows: AdminBookingSummary[]; query: Record<string, string> }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">{t.phase14e}</div><h1>{t.bookingsTitle}</h1><p>{t.bookingsDescription}</p></div></div>
    <section className="panel"><form className="filter-bar" method="get"><label>{t.bookingNumber}<input name="bookingNumber" defaultValue={query.bookingNumber} /></label><label>{t.status}<select name="status" defaultValue={query.status ?? ''}><option value="">{t.allStatuses}</option>{['REQUESTED', 'PRICE_CONFIRMED', 'PAYMENT_PENDING', 'CASH_SELECTED', 'PAYMENT_CONFIRMED', 'SEARCHING_FOR_TEAM', 'TEAM_ASSIGNED', 'TEAM_ACCEPTED', 'TEAM_ON_THE_WAY', 'CLEANING_STARTED', 'CLEANING_COMPLETED', 'PAYMENT_RECONCILIATION', 'COMPLETED', 'CANCELLED', 'NO_TEAM_AVAILABLE', 'REJECTED', 'TEAM_NO_SHOW', 'CUSTOMER_NO_SHOW', 'REFUND_PENDING', 'REFUNDED'].map(item => <option key={item} value={item}>{status(item)}</option>)}</select></label><label>{t.paymentMethod}<select name="paymentMethod" defaultValue={query.paymentMethod ?? ''}><option value="">{t.allMethods}</option><option value="ONLINE">ONLINE</option><option value="CASH">CASH</option></select></label><label>{t.customerId}<input name="customerId" defaultValue={query.customerId} /></label><label>{t.serviceId}<input name="serviceId" defaultValue={query.serviceId} /></label><label>{t.companyId}<input name="companyId" defaultValue={query.companyId} /></label><label>{t.teamId}<input name="teamId" defaultValue={query.teamId} /></label><label>{t.scheduledFrom}<input type="datetime-local" name="scheduledFrom" defaultValue={query.scheduledFrom} /></label><label>{t.scheduledTo}<input type="datetime-local" name="scheduledTo" defaultValue={query.scheduledTo} /></label><button type="submit">{t.applyFilters}</button><Link className="button-link" href={`/${locale}/operations/bookings`}>{t.clearFilters}</Link></form></section>
    <section className="panel"><div className="section-heading"><h2>{t.bookingResults}</h2><span>{rows.length} {t.results}</span></div>{!rows.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.booking}</th><th>{t.status}</th><th>{t.customer}</th><th>{t.service}</th><th>{t.scheduled}</th><th>{t.amount}</th><th>{t.assignment}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Link href={`/${locale}/operations/bookings/${row.id}`}>{row.bookingNumber}</Link></td><td>{status(row.status)}</td><td>{row.customer.name ?? row.customer.phone}<br /><small>{row.customer.status}</small></td><td>{locale === 'ar' ? row.service.nameAr : row.service.name}</td><td>{date(row.scheduledAt, locale)}</td><td>{row.price} {row.currency}</td><td>{row.currentAssignment ? `${row.currentAssignment.company.name} / ${row.currentAssignment.team.name}` : '—'}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}

export function BookingDetailView({ locale, booking, teams, canDispatch, canOperate }: { locale: Locale; booking: AdminBookingDetail; teams: import('../lib/admin-api').AdminTeam[]; canDispatch: boolean; canOperate: boolean }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">{t.phase14e}</div><h1>{t.booking} {booking.bookingNumber}</h1><p>{t.readOnlyDetail}</p></div><Link className="button-link" href={`/${locale}/operations/bookings`}>{t.backToList}</Link></div>
    <section className="detail-grid"><article className="panel"><h2>{t.summary}</h2><dl className="detail-list"><dt>{t.status}</dt><dd>{status(booking.status)}</dd><dt>{t.customer}</dt><dd>{booking.customer.name ?? booking.customer.phone}<br /><small>{booking.customer.phone} · {booking.customer.status}</small></dd><dt>{t.service}</dt><dd>{locale === 'ar' ? booking.service.nameAr : booking.service.name}</dd><dt>{t.amount}</dt><dd>{booking.price} {booking.currency}</dd><dt>{t.paymentMethod}</dt><dd>{booking.paymentMethod ?? '—'}</dd><dt>{t.scheduled}</dt><dd>{date(booking.scheduledAt, locale)}</dd><dt>{t.version}</dt><dd>{booking.version}</dd></dl></article><article className="panel"><h2>{t.assignmentHistory}</h2>{!booking.assignments.length ? <p className="empty-state">{t.noAssignments}</p> : <ul className="timeline">{booking.assignments.map(item => <li key={item.id}><strong>{status(item.status)} · {item.company.name} / {item.team.name}</strong><span>{date(item.assignedAt, locale)} · {item.company.status} / {item.team.status}</span><small>{item.reason ?? t.noReason}</small>{item.events.length > 0 && <small>{item.events.map(event => `${event.type} (${date(event.createdAt, locale)})`).join(' · ')}</small>}</li>)}</ul>}</article></section>
    <BookingActions locale={locale} booking={booking} teams={teams} canDispatch={canDispatch} canOperate={canOperate} />
    <section className="detail-grid"><article className="panel"><h2>{t.paymentState}</h2>{!booking.payments.length ? <p className="empty-state">{t.noPayment}</p> : <ul className="timeline">{booking.payments.map(payment => <li key={payment.id}><strong>{payment.method} · {payment.status}</strong><span>{payment.amount} {payment.currency} · {date(payment.createdAt, locale)}</span>{payment.cashCollection && <small>{t.cashCollection}: {payment.cashCollection.amount} · {t.collectedAt}: {date(payment.cashCollection.collectedAt, locale)} · {t.reconciledAt}: {payment.cashCollection.reconciledAt ? date(payment.cashCollection.reconciledAt, locale) : '—'}</small>}<small>{t.transactions}: {payment.transactions.length} · {t.refunds}: {payment.refunds.length}</small></li>)}</ul>}</article><article className="panel"><h2>{t.dispatchHistory}</h2>{!booking.dispatchAttempts.length ? <p className="empty-state">{t.noDispatchAttempts}</p> : <ol className="timeline">{booking.dispatchAttempts.map(attempt => <li key={attempt.id}><strong>#{attempt.sequence} · {status(attempt.outcome)}</strong><span>{date(attempt.createdAt, locale)}</span><small>{attempt.reason ?? t.noReason}</small></li>)}</ol>}</article></section>
    <section className="panel"><h2>{t.bookingHistory}</h2>{!booking.history.length ? <p className="empty-state">{t.emptyState}</p> : <ol className="timeline">{booking.history.map(item => <li key={item.id}><strong>{item.previousStatus ? `${status(item.previousStatus)} → ` : ''}{status(item.newStatus)}</strong><span>{date(item.createdAt, locale)}</span><small>{item.reason ?? t.noReason}</small></li>)}</ol>}</section>
  </div>;
}

export function DispatchView({ locale, monitoring, pendingOffers }: { locale: Locale; monitoring: DispatchMonitoring; pendingOffers: AdminBookingSummary[] }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">{t.phase14e}</div><h1>{t.dispatchTitle}</h1><p>{t.dispatchDescription}</p></div></div>
    <div className="dashboard-grid"><section className="panel"><h2>{t.dispatchBookings}</h2><CountList values={monitoring.bookings.map(row => ({ status: row.status, count: row._count._all }))} locale={locale} /></section><section className="panel"><h2>{t.dispatchAssignments}</h2><CountList values={monitoring.assignments.map(row => ({ status: row.status, count: row._count._all }))} locale={locale} /></section></div>
    <section className="panel"><h2>{t.pendingOffers}</h2>{!pendingOffers.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.booking}</th><th>{t.status}</th><th>{t.customer}</th><th>{t.assignment}</th><th>{t.scheduled}</th></tr></thead><tbody>{pendingOffers.map(row => <tr key={row.id}><td><Link href={`/${locale}/operations/bookings/${row.id}`}>{row.bookingNumber}</Link></td><td>{status(row.status)}</td><td>{row.customer.name ?? row.customer.phone}</td><td>{row.currentAssignment ? `${row.currentAssignment.company.name} / ${row.currentAssignment.team.name}` : '—'}</td><td>{date(row.scheduledAt, locale)}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel"><h2>{t.dispatchAttempts}</h2>{!monitoring.recentAttempts.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.booking}</th><th>{t.outcome}</th><th>{t.reason}</th><th>{t.created}</th></tr></thead><tbody>{monitoring.recentAttempts.map(row => <tr key={row.id}><td><Link href={`/${locale}/operations/bookings/${row.bookingId}`}>{row.bookingId}</Link></td><td>{status(row.outcome)}</td><td>{row.reason ?? '—'}</td><td>{date(row.createdAt, locale)}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}

export function UsersView({ locale, rows, query, canManage }: { locale: Locale; rows: AdminUserSummary[]; query: Record<string, string>; canManage: boolean }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14C</div><h1>{t.usersTitle}</h1><p>{t.usersDescription}</p></div></div><section className="panel"><form className="filter-bar" method="get"><label>{t.query}<input name="query" defaultValue={query.query} /></label><label>{t.status}<select name="status" defaultValue={query.status ?? ''}><option value="">{t.allStatuses}</option>{['ACTIVE', 'SUSPENDED', 'DEACTIVATED'].map(item => <option key={item}>{item}</option>)}</select></label><label>{t.role}<select name="role" defaultValue={query.role ?? ''}><option value="">{t.allRoles}</option>{['CUSTOMER', 'COMPANY_MANAGER', 'TEAM_LEADER_CLEANER', 'HOME_CLEAN_ADMIN', 'DISPATCHER'].map(item => <option key={item}>{item}</option>)}</select></label><button type="submit">{t.applyFilters}</button><Link className="button-link" href={`/${locale}/governance/users`}>{t.clearFilters}</Link></form></section><section className="panel"><div className="section-heading"><h2>{t.userResults}</h2><span>{rows.length} {t.results}</span></div>{!rows.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.name}</th><th>{t.phone}</th><th>{t.status}</th><th>{t.grants}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.name ?? '—'}</td><td>{row.phone}</td><td>{row.status}</td><td><Link href={`/${locale}/governance/users/${row.id}`}>{t.viewGrants}</Link></td></tr>)}</tbody></table></div>}</section>{canManage && <section className="panel"><ProvisionUserForm locale={locale} /></section>}</div>;
}

export function GrantsView({ locale, user, grants, canManage }: { locale: Locale; user: AdminUserSummary; grants: RoleGrant[]; canManage: boolean }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14C</div><h1>{t.grantsTitle}</h1><p>{user.name ?? user.phone}</p></div><Link className="button-link" href={`/${locale}/governance/users`}>{t.backToList}</Link></div><section className="panel">{!grants.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.role}</th><th>{t.companyId}</th><th>{t.teamId}</th><th>{t.actions}</th></tr></thead><tbody>{grants.map(row => <tr key={row.id}><td>{row.role}</td><td>{row.companyId ?? '—'}</td><td>{row.teamId ?? '—'}</td><td><RevokeGrantButton locale={locale} userId={user.id} grantId={row.id} canManage={canManage} /></td></tr>)}</tbody></table></div>}</section><section className="panel"><StatusControl locale={locale} userId={user.id} currentStatus={user.status} canManage={canManage} /></section></div>;
}

export function CustomersView({ locale, rows, query }: { locale: Locale; rows: AdminCustomerSummary[]; query: Record<string, string> }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14C</div><h1>{t.customersTitle}</h1><p>{t.customersDescription}</p></div></div><section className="panel"><form className="filter-bar" method="get"><label>{t.query}<input name="query" defaultValue={query.query} /></label><label>{t.status}<select name="status" defaultValue={query.status ?? ''}><option value="">{t.allStatuses}</option>{['ACTIVE', 'SUSPENDED', 'DEACTIVATED'].map(item => <option key={item}>{item}</option>)}</select></label><label>{t.locale}<select name="locale" defaultValue={query.locale ?? ''}><option value="">{t.allLocales}</option><option value="ar">ar</option><option value="en">en</option></select></label><button type="submit">{t.applyFilters}</button><Link className="button-link" href={`/${locale}/customers`}>{t.clearFilters}</Link></form></section><section className="panel"><div className="section-heading"><h2>{t.customerResults}</h2><span>{rows.length} {t.results}</span></div>{!rows.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.name}</th><th>{t.phone}</th><th>{t.locale}</th><th>{t.status}</th><th>{t.bookings}</th><th>{t.lastBooking}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Link href={`/${locale}/customers/${row.id}`}>{row.name ?? '—'}</Link></td><td>{row.phone}</td><td>{row.locale}</td><td>{row.status}</td><td>{row.bookingCount}</td><td>{row.lastBookingAt ? date(row.lastBookingAt, locale) : '—'}</td></tr>)}</tbody></table></div>}</section></div>;
}

export function CustomerDetailView({ locale, row, canManage }: { locale: Locale; row: AdminCustomerDetail; canManage: boolean }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14C</div><h1>{t.customerDetailTitle}</h1><p>{row.name ?? row.phone}</p></div><Link className="button-link" href={`/${locale}/customers`}>{t.backToList}</Link></div><section className="detail-grid"><article className="panel"><h2>{t.identitySummary}</h2><dl className="detail-list"><dt>{t.name}</dt><dd>{row.name ?? '—'}</dd><dt>{t.phone}</dt><dd>{row.phone}</dd><dt>{t.locale}</dt><dd>{row.locale}</dd><dt>{t.status}</dt><dd>{row.status}</dd><dt>{t.created}</dt><dd>{date(row.createdAt, locale)}</dd></dl></article><article className="panel"><h2>{t.customerCounts}</h2><dl className="detail-list"><dt>{t.addresses}</dt><dd>{row.counts.addresses}</dd><dt>{t.properties}</dt><dd>{row.counts.properties}</dd><dt>{t.bookings}</dt><dd>{row.counts.bookings}</dd></dl><p className="read-only-note">{t.customerPrivacy}</p></article></section><section className="panel"><StatusControl locale={locale} userId={row.userId} currentStatus={row.status} canManage={canManage} /></section><section className="panel"><h2>{t.recentBookings}</h2>{!row.recentBookings.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.booking}</th><th>{t.status}</th><th>{t.scheduled}</th><th>{t.amount}</th></tr></thead><tbody>{row.recentBookings.map(booking => <tr key={booking.id}><td>{booking.bookingNumber}</td><td>{booking.status}</td><td>{date(booking.scheduledAt, locale)}</td><td>{booking.price} {booking.currency}</td></tr>)}</tbody></table></div>}</section></div>;
}

export function AuditView({ locale, rows, query }: { locale: Locale; rows: AuditSummary[]; query: Record<string, string> }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14B</div><h1>{t.auditTitle}</h1><p>{t.auditDescription}</p></div></div><section className="panel"><form className="filter-bar" method="get"><label>{t.action}<input name="action" defaultValue={query.action} /></label><label>{t.resourceType}<input name="resourceType" defaultValue={query.resourceType} /></label><label>{t.resourceId}<input name="resourceId" defaultValue={query.resourceId} /></label><label>{t.requestId}<input name="requestId" defaultValue={query.requestId} /></label><button type="submit">{t.applyFilters}</button><Link className="button-link" href={`/${locale}/governance/audit`}>{t.clearFilters}</Link></form></section><section className="panel"><div className="section-heading"><h2>{t.auditResults}</h2><span>{rows.length} {t.results}</span></div>{!rows.length ? <p className="empty-state">{t.emptyState}</p> : <div className="table-wrap"><table><thead><tr><th>{t.created}</th><th>{t.actor}</th><th>{t.action}</th><th>{t.resource}</th><th>{t.reason}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Link href={`/${locale}/governance/audit/${row.id}`}>{date(row.createdAt, locale)}</Link></td><td>{row.actor?.name ?? row.actor?.phone ?? t.systemActor}</td><td>{row.action}</td><td>{row.resourceType} / {row.resourceId}</td><td>{row.reason ?? '—'}</td></tr>)}</tbody></table></div>}</section></div>;
}

export function AuditDetailView({ locale, row }: { locale: Locale; row: AuditDetail }) {
  const t = messagesFor(locale);
  return <div className="dashboard-stack"><div className="page-heading"><div><div className="phase-tag">14B</div><h1>{t.auditDetailTitle}</h1><p>{row.action} · {date(row.createdAt, locale)}</p></div><Link className="button-link" href={`/${locale}/governance/audit`}>{t.backToList}</Link></div><section className="detail-grid"><article className="panel"><h2>{t.summary}</h2><dl className="detail-list"><dt>{t.actor}</dt><dd>{row.actor?.name ?? row.actor?.phone ?? t.systemActor}</dd><dt>{t.resource}</dt><dd>{row.resourceType} / {row.resourceId}</dd><dt>{t.requestId}</dt><dd>{row.requestId ?? '—'}</dd><dt>{t.reason}</dt><dd>{row.reason ?? '—'}</dd></dl></article><article className="panel"><h2>{t.redactedPayload}</h2><pre className="json-view">{JSON.stringify({ before: row.before, after: row.after }, null, 2)}</pre></article></section></div>;
}
