export const bookingListSelect = {
  id: true,
  bookingNumber: true,
  status: true,
  paymentMethod: true,
  price: true,
  currency: true,
  scheduledAt: true,
  estimatedEndAt: true,
  createdAt: true,
} as const;

export const bookingSelect = {
  id: true,
  bookingNumber: true,
  customerId: true,
  serviceId: true,
  propertyId: true,
  addressId: true,
  status: true,
  paymentMethod: true,
  price: true,
  currency: true,
  scheduledAt: true,
  estimatedEndAt: true,
  instructions: true,
  version: true,
  createdAt: true,
  updatedAt: true,
  addressSnapshot: true,
  propertySnapshot: true,
  serviceSnapshot: true,
  locationLatitude: true,
  locationLongitude: true,
  extras: { select: { id: true, serviceExtraId: true, name: true, quantity: true, price: true }, orderBy: { id: 'asc' as const } },
  priceSnapshot: { select: { pricingVersion: true, basePrice: true, extrasTotal: true, adjustments: true, fees: true, discount: true, total: true, currency: true, breakdown: true } },
  history: { select: { id: true, previousStatus: true, newStatus: true, changedByUserId: true, changedByRole: true, reason: true, metadata: true, createdAt: true }, orderBy: { createdAt: 'asc' as const } },
  assignments: { select: { id: true, companyId: true, teamId: true, status: true, startsAt: true, endsAt: true, assignedAt: true, expiresAt: true, acceptedAt: true, reason: true, events: { select: { id: true, type: true, metadata: true, createdAt: true }, orderBy: { createdAt: 'asc' as const }, }, proofs: { select: { id: true, storageKey: true, mimeType: true, byteSize: true, createdAt: true }, orderBy: { createdAt: 'asc' as const } } }, orderBy: { assignedAt: 'asc' as const } },
  payments: { select: { id: true, method: true, status: true, amount: true, currency: true, provider: true, transactionReference: true, createdAt: true, updatedAt: true, transactions: { select: { id: true, type: true, amount: true, reference: true, createdAt: true }, orderBy: { createdAt: 'asc' as const } }, refunds: { select: { id: true, amount: true, status: true, reference: true, reason: true, createdAt: true, updatedAt: true }, orderBy: { createdAt: 'asc' as const } }, cashCollection: { select: { id: true, amount: true, collectedByUserId: true, collectedAt: true, reconciledAt: true } } }, orderBy: { createdAt: 'asc' as const } },
} as const;
